# Contains all constants used in the project

Nationality = 'Nationality'
Single_position = 'Single_position'
Position = 'Position'
Club = 'Club'
Sprint_Speed = 'Sprint_Speed'
Weight = 'Weight'
Height = 'Height'
Name = 'Name'
height_temp = 'height_temp'
height_temp1 = 'height_temp1'
height_mtr = 'height_mtr'
weight_temp = 'weight_temp'
weight_kg = 'weight_kg'
IMC = 'IMC'
count = 'count'
numbers_of_players_by_club_and_position = 'numbers_of_players_by_club_and_position'
top_sprint_speed_average = 'top_sprint_speed_average'
OVA = 'OVA'
row_number = 'row_number'
top10 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
overwrite = 'overwrite'
